#!/bin/bash

set -e

source /usr/libexec/s2i/env

if [ "$DEV_MODE" == true ] ; then
	set -x
fi

echo "---> Installing application source"
cp -Rfp /tmp/src/. ./

echo "---> Building your Deno application from source"

