#!/bin/bash

set -e

source /usr/libexec/s2i/env
cp -r /tmp/src/ /opt/app-root/
pushd /opt/app-root/src > /dev/null

echo "---> Bundling your Deno application"

TSCONFIG_FLAG=""
if [ ! -z "${TSCONFIG}" ]
then
  TSCONFIG_FLAG="-c ${TSCONFIG}"
  echo "---> Using TypeScript config ${TSCONFIG}"
fi

echo -e "Deno version:\n`deno --version`"
deno bundle ${TSCONFIG_FLAG} ${MAIN} > bundle.js
