#!/bin/bash

set -e

source /usr/libexec/s2i/env

echo "---> Bundling your Deno application"

TSCONFIG_FLAG=""
if [ ! -z "${TSCONFIG}" ]
then
  TSCONFIG_FLAG="-c ${TSCONFIG}"
  echo "---> Using TypeScript config ${TSCONFIG}"
fi

deno bundle ${TSCONFIG_FLAG} ${MAIN} > main.js
