#!/bin/sh

cat <<EOF
This is a S2I base image for Deno:
To use it, install S2I: https://github.com/openshift/source-to-image

Sample invocation:
s2i build https://github.com/nodeshift/ubi8-s2i-deno --context-dir=test/test-app/ nodeshift/ubi-s2i-deno:latest sample-app

You can then run the resulting image via:
docker run -p 8080:8080 sample-app
EOF
