#!/bin/sh

cat <<EOF
This is a S2I base image for Deno:
To use it, install S2I: https://github.com/openshift/source-to-image

Sample invocation using remote github repository:
$ s2i build https://github.com/dbevenius/ubi8-s2i-deno --context-dir=example-app danbev/ubi8-s2i-deno:latest deno-sample-app -e MAIN="src/welcome.ts" -e PERMISSIONS="--allow-read=/etc"

Sample invocation using local repository:
$ s2i build file:///\$PWD dbevenius/ubi8-s2i-deno:latest --context-dir=example-app deno-sample-app -e MAIN="src/welcome.ts" -e PERMISSIONS="--allow-read=/etc"

You can then run the resulting image via:
$ docker run -t sample-app
EOF
