---
name: check parent image

env:
  PARENT_IMAGE: registry.access.redhat.com/ubi9-minimal
  IMAGE_NAME: quay.io/ibotty/s2i-deno:latest

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *' # daily

jobs:
  check_outdated:
    name: Check for outdated parent container image
    runs-on: ubuntu-latest
    outputs:
      out-of-date: ${{ steps.check_outdated.outputs.out-of-date }}
    steps:
    - name: check for outdated base image
      id: check_outdated
      uses: twiddler/is-my-docker-parent-image-out-of-date@v1
      with:
        parent-image: ${{ env.PARENT_IMAGE }}
        my-image: ${{ env.IMAGE_NAME }}

  rebuild:
    name: Rebuilds if base image changed
    runs-on: ubuntu-latest
    needs: check_outdated
    if: ${{ needs.check_outdated.outputs.out-of-date == 'true' }}
    steps:
    - name: trigger rebuild
      uses: actions/github-script@v6
      if: ${{ env.release_version }}      
      with:
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: "container-build.yml",
            ref: "main",
            inputs: {
            }
          });
