---
name: build container on push

env:
  IMAGE_NAME: quay.io/ibotty/s2i-deno

on:
  workflow_dispatch:
  push:

jobs:
  latest_deno:
    name: deno version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_latest_deno.outputs.version }}
    steps:
    - name: Get latest deno release
      id: get_latest_deno
      shell: bash
      run: |
        set -euo pipefail
        get_latest_github_release() {
          local url="https://api.github.com/repos/$1/releases/latest"
          curl -fsSLH 'Accept: application/json' "$url" | jq -cr .tag_name
        }
        deno_version="$(get_latest_github_release denoland/deno)"
        echo "discovered  denoland/deno $deno_version"

        echo "version=$deno_version" >> $GITHUB_OUTPUT

  build:
    name: Trigger build of new image
    needs: latest_deno
    strategy:
      matrix:
        include:
        - tags: latest ${{ needs.latest_deno.outputs.version }}
          deno_version: ${{ needs.latest_deno.outputs.version }}
    uses: ./.github/workflows/container-build.yml
    with:
      deno_version: ${{ matrix.deno_version }}
      tags: ${{ matrix.tags }}
    secrets: inherit
