---
name: build container on push

env:
  IMAGE_NAME: quay.io/ibotty/s2i-deno

on:
  workflow_dispatch:
  push:

jobs:
  latest_deno:
    name: deno version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_latest_package.outputs.result }}
    steps:
    - name: Get latest package release
      id: get_latest_package
      uses: actions/github-script@v7
      with:
        retries: 3
        result-encoding: string
        script: |
          return await github.rest.repos.getLatestRelease({
            owner: "denoland",
            repo: "deno"
          }).then(r => r.data.tag_name)

  build:
    name: Trigger build of new image
    needs: latest_deno
    uses: ./.github/workflows/container-build.yml
    with:
      tags: latest ${{ needs.latest_deno.outputs.version }}
      deno_version: ${{ needs.latest_deno.outputs.version }}
    secrets: inherit
